"""DO NOT EDIT.

This file was autogenerated. Do not edit it by hand,
since your modifications would be overwritten.
"""

from keras_cv.src.models.segmentation.basnet.basnet import BASNet
from keras_cv.src.models.segmentation.deeplab_v3_plus.deeplab_v3_plus import (
    DeepLabV3Plus,
)
from keras_cv.src.models.segmentation.segformer.segformer import SegFormer
from keras_cv.src.models.segmentation.segment_anything.sam import (
    SegmentAnythingModel,
)
from keras_cv.src.models.segmentation.yolo_v8_segmentation.yolo_v8_segmentation import (
    YOLOV8Segmentation,
)
