"""DO NOT EDIT.

This file was autogenerated. Do not edit it by hand,
since your modifications would be overwritten.
"""

from keras_cv.src.models.object_detection.yolo_v8.yolo_v8_label_encoder import (
    YOLOV8LabelEncoder as LabelEncoder,
)
