name: 'devcontainer'
on: # rebuild any PRs and main branch changes
  pull_request:
    paths:
      - 'setup.*'
      - '.devcontainer/**'
      - 'workflows/**'
  push:
    paths:
      - 'setup.*'
      - '.devcontainer/**'
      - 'workflows/**'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v4

      - name: Build and run dev container task
        uses: devcontainers/ci@v0.3
        with:
          runCmd: pytest keras_cv/ --ignore keras_cv/models
